OP_CODE_DOWNLOAD = 1
OP_CODE_UPLOAD = 2
OP_CODE_UPLOAD_RESP = 3
OP_CODE_DOWNLOAD_RESP = 4
ACK_SIZE_RECEIVED = 5

MESSAGE_SIZE = 32
ENCODE_TYPE = 'utf-8'
CHUNK_SIZE = 1024
BUFF_SIZE = 1024
CHAR_DELIMITER = '|'
MAX_TIMEOUT = 10
WINDOW_SIZE = 10
SOCK_TIMEOUT = 0.1
